### ISSUE TITLE
Is there any sample?

### ISSUE THREAD

**Issue by tibitoth** [mthamil/CommandLine.Core#4]

**Comment by mthamil** [comment]
Actually, yes. I am "dogfooding" this library here: https://github.com/mthamil/Simple.Migrations.Tools.DotNet/tree/master/src/Simple.Migrations.Tools.DotNet
[https://avatars1.githubusercontent.com/u/1046029?s=400&v=4]<https://github.com/mthamil/Simple.Migrations.Tools.DotNet/tree/master/src/Simple.Migrations.Tools.DotNet>

mthamil/Simple.Migrations.Tools.DotNet<https://github.com/mthamil/Simple.Migrations.Tools.DotNet/tree/master/src/Simple.Migrations.Tools.DotNet>
A Simple.Migrations console runner that uses the dotnet CLI. - mthamil/Simple.Migrations.Tools.DotNet
github.com


________________________________

**Comment by tibitoth** [comment]
I'm just wondering is this different from Generic Host?

**Comment by mthamil** [comment]
Well, I started it before generic host was really a thing. They are without a doubt similar concepts, though. I believe I read that the generic host is not favoring/supporting the Startup class approach, so there are some differences. I wouldn't blame you for choosing generic host. I will need to dig in more at some point to see if there is an opportunity for unification.
________________________________

**Comment by tibitoth** [comment]
Generic host will support Startup class in ASP.NET Core 3.0

**Comment by mthamil** [comment]
Good to know, thanks. I have some reading to do, apparently.
________________________________

**Comment by tibitoth** [comment]
Another question which one is better from your sight: 
- https://github.com/commandlineparser/commandline
- https://github.com/natemcmaster/CommandLineUtils

I see you are using the library from @natemcmaster

**Comment by mthamil** [comment]
I have used CommandLineParser before, and it is a fine library. However, I prefer CommandLineUtils these days because it is more flexible in some ways. I believe it supports more complex command line features. At the same time, it also provides a more opinionated way to structure your application if you wish, whereas CommandLineParser is more on the "just parsing" side which some may consider more pure or focused. I tend to prefer the "fluent" and convention-based style vs attributes with CommandLineUtils. On the other hand, CommandLineParser has been around longer, probably has better help generation support, and also has an "unparse" feature.
________________________________

**Comment by tibitoth** [comment]
Thank you for your answer
